"""
Merge spreadsheet + Mural notes into one markdown bundle for brand_run / concept_run.

Usage:
  python scripts/merge_brand_research.py

Reads (if present):
  brand/research/characteristics.csv
  brand/research/USER-RESEARCH.md
  brand/research/mural/notes.md
  brand/research/mural/link.txt

Writes:
  brand/research/research-bundle.md
"""
from __future__ import annotations

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESEARCH = ROOT / "brand" / "research"
CSV_PATH = RESEARCH / "characteristics.csv"
OPTIONS_PATH = RESEARCH / "positioning-options.json"
OUT_PATH = RESEARCH / "research-bundle.md"


def _read_optional(path: Path) -> str:
    if path.is_file():
        return path.read_text(encoding="utf-8").strip()
    return ""


def _load_csv_rows() -> list[dict[str, str]]:
    if not CSV_PATH.is_file():
        return []
    with CSV_PATH.open(encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


def _section_csv(rows: list[dict[str, str]]) -> str:
    if not rows:
        return (
            "_No `characteristics.csv` yet. Export your spreadsheet using "
            "`characteristics.template.csv` — see `brand/research/IMPORT.md`._\n"
        )

    lines = [
        "## Spreadsheet: brand characteristics\n",
        f"_{len(rows)} rows from characteristics.csv_\n",
    ]
    for row in rows:
        name = row.get("brand_name", "").strip() or "(unnamed)"
        in_line = (row.get("in_line") or "").strip().lower()
        lines.append(f"### {name} (`in_line={in_line or '?'}`)\n")
        for key in (
            "url",
            "category",
            "positioning_id",
            "positioning_name",
            "lane",
            "use_cases",
            "adjectives",
            "visual_design_notes",
            "product_traits",
            "why_in_or_out",
        ):
            val = (row.get(key) or "").strip()
            if val:
                lines.append(f"- **{key}:** {val}")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    rows = _load_csv_rows()
    mural_notes = _read_optional(RESEARCH / "mural" / "notes.md")
    mural_links = _read_optional(RESEARCH / "mural" / "link.txt")
    user_research = _read_optional(RESEARCH / "USER-RESEARCH.md")

    mural_png = list((RESEARCH / "mural").glob("*.png")) if (RESEARCH / "mural").is_dir() else []

    parts = [
        "# PEP research bundle (for brand agent)\n",
        "_Auto-generated by `scripts/merge_brand_research.py`. Do not edit by hand — re-run the script after updating CSV/Mural._\n",
        "---\n",
        "## Mural\n",
    ]
    if mural_links:
        parts.append("**Board link(s):**\n")
        for line in mural_links.splitlines():
            line = line.strip()
            if line:
                parts.append(f"- {line}")
        parts.append("")
    if mural_png:
        parts.append("**PNG exports (use vision in brand_run):**\n")
        for p in sorted(mural_png):
            rel = p.relative_to(ROOT).as_posix()
            parts.append(f"- `{rel}`")
        parts.append("")
    else:
        parts.append(
            "_No PNG in `brand/research/mural/` yet. Export board as `board.png` — see IMPORT.md._\n"
        )
    if mural_notes:
        parts.append("### Pasted Mural notes\n")
        parts.append(mural_notes)
        parts.append("\n")

    options = _read_optional(OPTIONS_PATH)
    parts.append("---\n")
    parts.append("## Product positioning options (3 directions)\n")
    if options:
        parts.append(f"_From `positioning-options.json`_\n\n```json\n{options}\n```\n")
    else:
        parts.append("_Run `python scripts/parse_positioning_options.py`._\n")
    parts.append("---\n")
    parts.append(_section_csv(rows))
    parts.append("---\n")
    parts.append("## Manual research (USER-RESEARCH.md)\n")
    parts.append(user_research or "_Empty — optional supplement to spreadsheet._\n")

    OUT_PATH.write_text("\n".join(parts), encoding="utf-8")
    print(f"Wrote {OUT_PATH.relative_to(ROOT)}")
    if not CSV_PATH.is_file():
        print("Tip: add brand/research/characteristics.csv from your spreadsheet.")
    if not mural_png:
        print("Tip: add brand/research/mural/board.png from Mural export.")


if __name__ == "__main__":
    main()
