"""JSON schema for brand_run output (active positioning)."""

BRAND_BUNDLE_SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "properties": {
        "positioning": {
            "type": "object",
            "additionalProperties": False,
            "properties": {
                "version": {"type": "integer"},
                "activeId": {"type": "integer"},
                "activeSlug": {"type": "string"},
                "activeName": {"type": "string"},
                "brand": {"type": "string"},
                "domain": {"type": "string"},
                "oneLiner": {"type": "string"},
                "positioningStatement": {"type": "string"},
                "audience": {"type": "array", "items": {"type": "string"}},
                "occasions": {"type": "array", "items": {"type": "string"}},
                "personalityAdjectives": {"type": "array", "items": {"type": "string"}},
                "voice": {
                    "type": "object",
                    "additionalProperties": False,
                    "properties": {
                        "tone": {"type": "string"},
                        "tagline": {"type": "string"},
                        "avoidWords": {"type": "array", "items": {"type": "string"}},
                    },
                    "required": ["tone", "tagline", "avoidWords"],
                },
                "visual": {
                    "type": "object",
                    "additionalProperties": False,
                    "properties": {
                        "colorsFromBrandJson": {"type": "boolean"},
                        "mood": {"type": "string"},
                        "photography": {"type": "string"},
                        "typography": {"type": "string"},
                        "designConcept": {"type": "string"},
                        "rejectLooks": {"type": "array", "items": {"type": "string"}},
                    },
                    "required": [
                        "colorsFromBrandJson",
                        "mood",
                        "photography",
                        "typography",
                        "designConcept",
                        "rejectLooks",
                    ],
                },
                "inLineBrands": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": False,
                        "properties": {
                            "name": {"type": "string"},
                            "url": {"type": "string"},
                            "category": {"type": "string"},
                            "drinkTypeFit": {"type": "string"},
                            "why": {"type": "string"},
                            "adjectives": {"type": "array", "items": {"type": "string"}},
                            "designPatterns": {"type": "array", "items": {"type": "string"}},
                        },
                        "required": [
                            "name",
                            "why",
                            "adjectives",
                            "designPatterns",
                            "category",
                            "url",
                            "drinkTypeFit",
                        ],
                    },
                },
                "positioningFitTypeMismatch": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": False,
                        "properties": {
                            "name": {"type": "string"},
                            "url": {"type": "string"},
                            "category": {"type": "string"},
                            "drinkTypeFit": {"type": "string"},
                            "whyBrandingFits": {"type": "string"},
                            "positioningMismatch": {"type": "string"},
                            "typeMismatch": {"type": "string"},
                        },
                        "required": [
                            "name",
                            "url",
                            "category",
                            "drinkTypeFit",
                            "whyBrandingFits",
                            "positioningMismatch",
                            "typeMismatch",
                        ],
                    },
                },
                "peerBrandsOtherPositionings": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": False,
                        "properties": {
                            "name": {"type": "string"},
                            "positioning_id": {"type": "integer"},
                            "drinkTypeFit": {"type": "string"},
                            "positioningMismatch": {"type": "string"},
                            "whyNotActive": {"type": "string"},
                        },
                        "required": [
                            "name",
                            "positioning_id",
                            "drinkTypeFit",
                            "positioningMismatch",
                            "whyNotActive",
                        ],
                    },
                },
                "antiReferences": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": False,
                        "properties": {
                            "name": {"type": "string"},
                            "why": {"type": "string"},
                        },
                        "required": ["name", "why"],
                    },
                },
                "layoutOnlyReferences": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": False,
                        "properties": {
                            "name": {"type": "string"},
                            "url": {"type": "string"},
                            "patterns": {"type": "array", "items": {"type": "string"}},
                        },
                        "required": ["name", "patterns", "url"],
                    },
                },
                "brandFitRules": {"type": "array", "items": {"type": "string"}},
            },
            "required": [
                "version",
                "activeId",
                "activeSlug",
                "activeName",
                "brand",
                "domain",
                "oneLiner",
                "positioningStatement",
                "audience",
                "occasions",
                "personalityAdjectives",
                "voice",
                "visual",
                "inLineBrands",
                "positioningFitTypeMismatch",
                "peerBrandsOtherPositionings",
                "antiReferences",
                "layoutOnlyReferences",
                "brandFitRules",
            ],
        },
        "brandGuidelinesMarkdown": {"type": "string"},
    },
    "required": ["positioning", "brandGuidelinesMarkdown"],
}
